# Generated by Django 5.1.5 on 2025-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defaults/product_placeholder.png', upload_to='products/'),
        ),
    ]
