# Generated by Django 5.1.5 on 2025-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='TempValue', max_length=255),
            preserve_default=False,
        ),
    ]
